// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddScanDirectory(arg1) {
  return window['go']['main']['App']['AddScanDirectory'](arg1);
}

export function ClearHistory() {
  return window['go']['main']['App']['ClearHistory']();
}

export function GetActivityLog(arg1) {
  return window['go']['main']['App']['GetActivityLog'](arg1);
}

export function GetEventCounts() {
  return window['go']['main']['App']['GetEventCounts']();
}

export function GetHealthResults() {
  return window['go']['main']['App']['GetHealthResults']();
}

export function GetLogCounts(arg1) {
  return window['go']['main']['App']['GetLogCounts'](arg1);
}

export function GetLogs(arg1) {
  return window['go']['main']['App']['GetLogs'](arg1);
}

export function GetLogsForAI(arg1) {
  return window['go']['main']['App']['GetLogsForAI'](arg1);
}

export function GetServerByPort(arg1) {
  return window['go']['main']['App']['GetServerByPort'](arg1);
}

export function GetServers() {
  return window['go']['main']['App']['GetServers']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function HasNotificationPermission() {
  return window['go']['main']['App']['HasNotificationPermission']();
}

export function KillProcess(arg1) {
  return window['go']['main']['App']['KillProcess'](arg1);
}

export function RemoveScanDirectory(arg1) {
  return window['go']['main']['App']['RemoveScanDirectory'](arg1);
}

export function RequestNotificationPermission() {
  return window['go']['main']['App']['RequestNotificationPermission']();
}

export function ResetSettings() {
  return window['go']['main']['App']['ResetSettings']();
}

export function RunHealthCheck(arg1) {
  return window['go']['main']['App']['RunHealthCheck'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}
