// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {activitylog} from '../models';
import {healthcheck} from '../models';
import {logcapture} from '../models';
import {processmonitor} from '../models';
import {settings} from '../models';

export function AddScanDirectory(arg1:string):Promise<void>;

export function ClearHistory():Promise<void>;

export function GetActivityLog(arg1:activitylog.ActivityFilter):Promise<Array<activitylog.ActivityEvent>>;

export function GetEventCounts():Promise<Record<activitylog.EventType, number>>;

export function GetHealthResults():Promise<Array<healthcheck.HealthResult>>;

export function GetLogCounts(arg1:number):Promise<Record<logcapture.LogLevel, number>>;

export function GetLogs(arg1:logcapture.LogFilter):Promise<Array<logcapture.LogLine>>;

export function GetLogsForAI(arg1:number):Promise<string>;

export function GetMonitorStatus():Promise<processmonitor.MonitorStatus>;

export function GetServerByPort(arg1:number):Promise<processmonitor.Server>;

export function GetServers():Promise<Array<processmonitor.Server>>;

export function GetSettings():Promise<settings.Config>;

export function HasNotificationPermission():Promise<boolean>;

export function KillProcess(arg1:number):Promise<void>;

export function RemoveScanDirectory(arg1:string):Promise<void>;

export function RequestNotificationPermission():Promise<void>;

export function ResetSettings():Promise<void>;

export function RunHealthCheck(arg1:Array<number>):Promise<Array<healthcheck.HealthResult>>;

export function SaveSettings(arg1:settings.Config):Promise<void>;
